sudo: false
language: go
go:
    - 1.9

script:
    - go get github.com/softlayer/softlayer-go/...
    - go get github.com/hashicorp/terraform
    - 'if [ "${TRAVIS_BUILD_DIR}" != "${GOPATH}/src/github.com/softlayer/terraform-provider-softlayer" ]; then ln -s "${TRAVIS_BUILD_DIR}" "${GOPATH}/src/github.com/softlayer/terraform-provider-softlayer"; fi'
    - make

